### PR TITLE
FFmpeg : muxing

### PR DESCRIPTION
**Pull request by pfeatherstone**
Muxing. Nearly there. This only contains 1 example. I'll drop examples in separate PRs.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
@davisking nudge

**Comment by davisking** [comment]
Nice, thanks for the PR :)

**Comment by pfeatherstone** [comment]
Oh thanks! And happy holidays!

**Comment by davisking** [comment]
> Oh thanks! And happy holidays! 

You too :)

**Pull request merged**
