### PR TITLE
Add expanded pixel color channel depth options #1

### PR DESCRIPTION
**Pull request by frankiek3**
1st Stage
- Adds ability to specify pixel depth using template arguments
- Uses pixel_traits for color space convertions instead of relying on 8-bit
- Changes some formatting

### CODE REVIEW

**Comment by frankiek3** [comment]
From #513

**Comment by davisking** [comment]
Cool.  I assume you are still working on this.  So far it seems sensible.  But could you try to avoid making whitespace only changes?  I looked over it and it's harder to review than needed since a lot of the changes aren't really changes, but just modified whitespace.

Also, another thing to watch out for is that the existing image processing routines aren't disturbed.  For instance, it's likely that there are some routines with contracts that say something like "I'll take in any RGB pixel" and maybe there is something about them that only makes sense for 8bit pixels.  Finding that kind of thing will require some looking around and testing.  Also, if you are going to make it templated you might as well let RGB pixels contain floats since I know people will ask for that.  Although that might complicate things.

**Comment by frankiek3** [comment]
Sorry about the whitespace changes if you want I'll seperate it into 2 commits; One for formatting and one for then changes.
I could also just do one with the real changes, but the new file seems to me to be more readable.

Notes:
I reworked the alpha blending, as the compiler should take care of promoting types.

For some of the color space conversations that used HSL2RGB and RGB2HSL, I only allowed 8-bit using std::is_same
It might be better to use an optional external lib like imagemagick if further conversations are necessary using the new types.

I didn't touch serialization​ yet, since I don't want to mess up backwords compatibility.

So far the changes don't use the expanded color depth. I'll still need to add the commits that do.

**Comment by davisking** [comment]
Yeah, don't include formatting in this PR.  Maybe in another one later on.

I don't want to add any dependencies, especially for something as minor as color conversion.  And in any event, the current behavior needs to be preserved so existing code doesn't break, especially the unit tests which aren't passing for this PR.  

Also, one of the important things about assign_pixel() and it's related tools is that they are able to convert from any pixel type to any other.  So that's definitely required.  For instance, the reason load_image() works on any image type is because it calls assign_pixel() to store the pixel value into the output image.  But if some color space conversions aren't allowed then things like load_image() will fail in ways users won't understand and are generally irritating.  The need to support all possible combinations of color space conversions is one of the main reasons why I was, and am, a bit wary about trying to have templated pixels.  But if you get it all working that would be super :)

**Comment by fenollp** [comment]
You can ignore whitespace on review on Github https://github.com/blog/967-github-secrets

**Pull request closed without merging**
