### PR TITLE
Bessel fix for MSVC

### PR DESCRIPTION
**Pull request by pfeatherstone**
This should fix the issue raised in #2627

### CODE REVIEW

**Comment by davisking** [comment]
Huh, yeah, so that works for you @VisionEp1?

**Comment by davisking** [comment]
Well, let's merge it and see what people say.  Thanks for the fix @pfeatherstone  :)

**Comment by VisionEp1** [comment]
srry was asleep :),
can confirm it works 
thanks again!

And sorry I couldn't provide the fix myself I never worked with the common type thing we use boost instead still...

**Comment by davisking** [comment]
Sweet, no worries :)

**Pull request merged**
