### PR TITLE
Make GitHub actions use `gcc-11` in parallel with the default `gcc-9` that comes with `ubuntu-latest`

### LINKED ISSUE #2508: Make Github Actions run on default gcc version from ubuntu-latest, and also gcc-11
Would be cool if github actions tests ran with multiple versions of GCC.  At some point they are going to limit us though.   But it would be cool if there was an ubuntu-gcc11 mode in the build matrix in addition to the default gcc. Maybe it would all run in parallel.

_Originally posted by @davisking in https://github.com/davisking/dlib/issues/2506#issuecomment-1037239057_

### PR DESCRIPTION
**Pull request by reunanen**
Resolves #2508.

At some point, not using a matrix might be more convenient.

### CODE REVIEW

**Comment by reunanen** [comment]
Also, no idea if there are cleaner ways to do this...

**Comment by arrufat** [comment]
I also need to read more on the GitHub actions documentation (and see more examples)

**Comment by reunanen** [comment]
Fortunately the script is still quite simple, so it's not too difficult to go back and forth.

**Comment by reunanen** [comment]
I mean, if you just want to list a bunch of jobs without using a matrix, for example.

**Pull request closed without merging**
