### PR TITLE
Add an option to force static runtime

### LINKED ISSUE #1846: jpeg.lib(jdatadst.c.obj) : error LNK2001: unresolved external symbol __imp_ferror
## Expected Behavior

successful link

## Current Behavior

cmake output:
```
2019-07-27T10:34:47.2462066Z CMake Warning (dev) in CMakeLists.txt:
2019-07-27T10:34:47.2462604Z   No project() command is present.  The top-level CMakeLists.txt file must
2019-07-27T10:34:47.2463339Z   contain a literal, direct call to the project() command.  Add a line of
2019-07-27T10:34:47.2463569Z   code such as
2019-07-27T10:34:47.2464090Z 
2019-07-27T10:34:47.2464425Z     project(ProjectName)
2019-07-27T10:34:47.2464608Z 
2019-07-27T10:34:47.2465605Z   near the top of the file, but after cmake_minimum_required().
2019-07-27T10:34:47.2465919Z 
2019-07-27T10:34:47.2466497Z   CMake is pretending there is a "project(Project)" command on the first
2019-07-27T10:34:47.2466880Z   line.
2019-07-27T10:34:47.2467358Z This warning is for project developers.  Use -Wno-dev to suppress it.
2019-07-27T10:34:47.2467500Z 
2019-07-27T10:34:49.8834395Z -- The C compiler identification is MSVC 19.0.24234.1
2019-07-27T10:34:50.6939330Z -- The CXX compiler identification is MSVC 19.0.24234.1
2019-07-27T10:34:50.7338415Z -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
2019-07-27T10:34:52.7226232Z -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
2019-07-27T10:34:52.7257070Z -- Detecting C compiler ABI info
2019-07-27T10:34:53.4004593Z -- Detecting C compiler ABI info - done
2019-07-27T10:34:53.4028102Z -- Detecting C compile features
2019-07-27T10:34:53.4038630Z -- Detecting C compile features - done
2019-07-27T10:34:53.4146628Z -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
2019-07-27T10:34:54.0299834Z -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
2019-07-27T10:34:54.0322802Z -- Detecting CXX compiler ABI info
2019-07-27T10:34:54.6412556Z -- Detecting CXX compiler ABI info - done
2019-07-27T10:34:54.6433381Z -- Detecting CXX compile features
2019-07-27T10:34:55.9678813Z -- Detecting CXX compile features - done
2019-07-27T10:34:56.1217778Z -- Found PythonInterp: D:/bld/dlib_1564223517504/_h_env/python.exe (found version "3.6.7") 
2019-07-27T10:34:56.1728475Z -- Found PythonLibs: D:/bld/dlib_1564223517504/_h_env/libs/Python36.lib
2019-07-27T10:34:56.1832527Z -- pybind11 v2.2.2
2019-07-27T10:34:56.1866587Z -- Using CMake version: 3.15.0
2019-07-27T10:34:56.1866972Z -- Compiling dlib version: 19.17.0
2019-07-27T10:35:00.4445088Z -- SSE4 instructions can be executed by the host processor.
2019-07-27T10:35:03.8103918Z -- AVX instructions can be executed by the host processor.
2019-07-27T10:35:04.1615304Z -- Looking for sys/types.h
2019-07-27T10:35:04.7680915Z -- Looking for sys/types.h - found
2019-07-27T10:35:04.7691534Z -- Looking for stdint.h
2019-07-27T10:35:05.3651772Z -- Looking for stdint.h - found
2019-07-27T10:35:05.3664567Z -- Looking for stddef.h
2019-07-27T10:35:05.9887758Z -- Looking for stddef.h - found
2019-07-27T10:35:05.9892767Z -- Check size of void*
2019-07-27T10:35:06.6375389Z -- Check size of void* - done
2019-07-27T10:35:06.6380319Z -- Enabling AVX instructions
2019-07-27T10:35:10.0273753Z -- Found ZLIB: D:/bld/dlib_1564223517504/_h_env/Library/lib/z.lib (found version "1.2.11") 
2019-07-27T10:35:10.1136041Z -- Found PNG: D:/bld/dlib_1564223517504/_h_env/Library/lib/libpng.lib (found version "1.6.35") 
2019-07-27T10:35:10.1509169Z -- Found JPEG: D:/bld/dlib_1564223517504/_h_env/Library/lib/jpeg.lib (found version "90") 
2019-07-27T10:35:10.1525436Z -- Searching for BLAS and LAPACK
2019-07-27T10:35:10.1526287Z -- Searching for BLAS and LAPACK
2019-07-27T10:35:10.4854335Z -- Looking for pthread.h
2019-07-27T10:35:12.0344028Z -- Looking for pthread.h - not found
2019-07-27T10:35:12.0366068Z -- Found Threads: TRUE  
2019-07-27T10:35:12.2275493Z CMake Warning (dev) at D:/bld/dlib_1564223517504/_build_env/Library/share/cmake-3.15/Modules/FindCUDA.cmake:547 (if):
2019-07-27T10:35:12.2276098Z   Policy CMP0054 is not set: Only interpret if() arguments as variables or
2019-07-27T10:35:12.2276868Z   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
2019-07-27T10:35:12.2277221Z   details.  Use the cmake_policy command to set the policy and suppress this
2019-07-27T10:35:12.2277740Z   warning.
2019-07-27T10:35:12.2278039Z 
2019-07-27T10:35:12.2278672Z   Quoted variables like "MSVC" will no longer be dereferenced when the policy
2019-07-27T10:35:12.2279025Z   is set to NEW.  Since the policy is not set the OLD behavior will be used.
2019-07-27T10:35:12.2279511Z Call Stack (most recent call first):
2019-07-27T10:35:12.2280438Z   D:/bld/dlib_1564223517504/work/dlib/CMakeLists.txt:608 (find_package)
2019-07-27T10:35:12.2280838Z This warning is for project developers.  Use -Wno-dev to suppress it.
2019-07-27T10:35:12.2281178Z 
2019-07-27T10:35:12.2809366Z CUDA_TOOLKIT_ROOT_DIR not found or specified
2019-07-27T10:35:12.3814445Z -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
2019-07-27T10:35:12.3847366Z -- DID NOT FIND CUDA
2019-07-27T10:35:12.3853649Z -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
2019-07-27T10:35:12.3854537Z -- C++11 activated.
2019-07-27T10:35:12.3911553Z -- Configuring done
2019-07-27T10:35:12.5558776Z -- Generating done
2019-07-27T10:35:12.5622070Z -- Build files have been written to: D:/bld/dlib_1564223517504/work/build
2019-07-27T10:35:12.5628734Z -- Cache values
```

build output:
```
2019-07-27T10:41:41.6926049Z    Creating library dlib.lib and object dlib.exp
2019-07-27T10:41:41.6927803Z LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
2019-07-27T10:41:41.6928080Z jpeg.lib(jdatadst.c.obj) : error LNK2001: unresolved external symbol __imp_ferror
2019-07-27T10:41:41.6928276Z jpeg.lib(jmemansi.c.obj) : error LNK2001: unresolved external symbol __imp_tmpfile
2019-07-27T10:41:41.6928664Z dlib.cp36-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
```

## Steps to Reproduce

cmake script:
```
cmake -LAH -G"NMake Makefiles"                ^
  -DCMAKE_BUILD_TYPE=Release                  ^
  -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%"      ^
  -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"   ^
  -DDLIB_LINK_WITH_SQLITE3=OFF                ^
  ../tools/python
if errorlevel 1 exit 1

cmake --build .
if errorlevel 1 exit 1
```

installed dependencies: jpeg/libpng/python3.7/pybind11/numpy

* **Version**: 
19.17

* **Where did you get dlib**: 
github

* **Platform**: 
windows 64bits

* **Compiler**: 
msvc 2015

### PR DESCRIPTION
**Pull request by jschueller**
Forcing the static runtime results in undefined symbols in dependencies using another runtime 
In general its a bad idea to change the runtime, as cl warns:
```
cl : Command line warning D9025 : overriding '/MD' with '/MT'
```

Closes #1846

### CODE REVIEW

**Comment by davisking** [comment]
This seems like the wrong solution.  What happens if you use the latest copy of dlib from github, without any modifications?

**Comment by jschueller** [comment]
@davisking  I get exactly the same issue with master.

**Comment by davisking** [comment]
Oops, the build settings weren't quite what they should have been.  I just pushed a change, try the latest code now.

**Comment by jschueller** [comment]
I dont want to rebuild libjpeg; this will eat some CI time and the package will be bigger.

**Comment by davisking** [comment]
Well, the change you were proposing will break many other users. Which is how it got to be in the cmake scripts in the first place.

You can make a cmake variable that toggles it if you like though. But it must be on by default.

**Comment by jschueller** [comment]
I think I'll manually patch dlib, imho forcing another runtime is a very bad idea in the first place.

**Comment by davisking** [comment]
I wouldn't do it if it didn't result in me getting a flood of questions
from people confused about missing visual studio runtime dlls :(

**Comment by jschueller** [comment]
@davisking I added an option to toggle it

**Comment by davisking** [comment]
Thanks, looks good.

**Pull request merged**
