### PR TITLE
FFmpeg : API change to decoder and demuxer

### PR DESCRIPTION
**Pull request by pfeatherstone**
The suggested API changes defer resizing and resampling to `read()` call site. This allows us to more easily implement something like:
```
template<class image_type>
bool read(image_type& img)
```
Also, there is no reason why you should specify in the constructor how you're going to resize or resample stuff.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
Still WIP. Need to amend the tests and check i have actually made things simpler.

**Comment by pfeatherstone** [comment]
Do we really want all the docs in a separate `_abstract.h` file? I'm finding it tiresome synchronizing all the files. Wouldn't it be best to inline the docs in the actual code? We've split declarations from definitions already so maybe it would be ok and the code wouldn't look so disjoint?

**Comment by davisking** [comment]
> Do we really want all the docs in a separate `_abstract.h` file? I'm finding it tiresome synchronizing all the files. Wouldn't it be best to inline the docs in the actual code? We've split declarations from definitions already so maybe it would be ok and the code wouldn't look so disjoint? It's also easier to notice missing or old docs.

That's fine, so long as the headers are organized such that only public API stuff is in the header and/or only public API stuff is at the top.  So like, no `detail` namespace stuff at the top.  Either somehow move that down below the big warning comment about "implementation details below, don't look at this users!" kind of comment or put the detail namespace stuff in a separate detail header.

I.e. whatever makes it so there is some file that when someone looks at they see only information on the public API.

**Comment by pfeatherstone** [comment]
Thanks. I think it's worth getting all of this right before we cut a release. Though I'm pretty sure @arrufat and I are the only users at the moment so we have a bit of freedom I think ...

**Pull request closed without merging**
