### PR TITLE
Draw string on images

### PR DESCRIPTION
**Pull request by arrufat**
As discussed in #2264 with @pfeatherstone.

It's almost the same as the one defined in `fonts.h` for the gui widgets.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
Awesome! Looking forward to this. I imagine dlib users will be very happy with this and will probably be able to remove opencv as a massive dependency.

**Comment by davisking** [comment]
Nice, looks good.  Can you add a small test that does something like draws "cat" into a small image and checks that the expected result is obtained?  You could use `file_to_code_ex.cpp` to embed the correct image into the test code.

**Comment by arrufat** [comment]
Yes, I was wondering how to test it systematically.

Let me make sure I understand what you mean:
- embed a target image with the string already drawn (a small black image with cat written in white)
- generate a black image of the same size, write "cat" at the same position in white
- compare both images

**Comment by davisking** [comment]
> Yes, I was wondering how to test it systematically.
> 
> Let me make sure I understand what you mean:
> 
> * embed a target image with the string already drawn (a small black image with cat written in white)
> * generate a black image of the same size, write "cat" at the same position in white
> * compare both images

Yep.

**Comment by davisking** [comment]
Sweet, thanks for another PR :)

**Pull request merged**
