### PR TITLE
Make Github Actions build more stuff (in particular, the examples)

### PR DESCRIPTION
**Pull request by reunanen**
Thought it might be nice to have Github Actions build the examples, too? Just to catch as many issues as soon as possible?

Apparently there's some issue with the Windows builds (think @arrufat ran into that as well?), but I don't think this needs to prevent us from doing it on the other OSes/compilers?

### CODE REVIEW

**Comment by arrufat** [comment]
With debug builds, windows compilation was timing out (that might be solved with parallel builds) and some times I ran out of RAM... but it seems to work now 😕 🤔

**Comment by davisking** [comment]
Sweet

**Comment by davisking** [comment]
I just added `--parallel 8` to the builds too :)

**Comment by arrufat** [comment]
Apparently, builds fail now.
On macOS because of the MPC test condition, which it's apparently too strict. I noticed that already and fixed in PR #2499.
And, I can't get the logs as per why it's failing on Linux…

**Comment by davisking** [comment]
Yeah.  It seems like there is only actually 2 cores on these github machines.  I'm trying less parallelism now.

I also suspect the MPC code is failing on mac because the build in BLAS and LAPACK on mac machines is often awful.  Going to set it to not use that on mac and see what happens.

**Comment by reunanen** [comment]
Yep, `--parallel 8` indeed appeared to be too much for building the examples. I'm guessing the build agent just runs out of RAM.

**Pull request merged**
