### PR TITLE
CMake: Make dependencies private

### PR DESCRIPTION
**Pull request by jschueller**
most of them can be made private

### CODE REVIEW

**Comment by pfeatherstone** [comment]
I think we should not have those lists and just use `target_sources()`, `target_include_directories()`, `target_link_libraries()`, etc. I had a PR at some point that cleaned all of this up, including making things private, but got a bit stuck on the python binding things. I wanted a single CMakeLists.txt file that built the library, python bindings, and unit tests, rather than have multiple CMakeLists.txt files for each one.

**Comment by pfeatherstone** [comment]
Feel free to use https://github.com/davisking/dlib/pull/2672 this if it helps. Not perfect I know and maybe i was a bit too ambitious as I'm not a cmake expert.

**Comment by jschueller** [comment]
lets do it step by step

**Comment by jschueller** [comment]
this closes #3694 @davisking

**Comment by davisking** [comment]
Just tested this a bit, needed one tweak, but otherwise looks good.  Thanks for the PR :)

**Pull request merged**
