### PR TITLE
Fix computation of the Barlow Twins loss gradient

### PR DESCRIPTION
**Pull request by arrufat**
When computing the gradient for the off diagonal terms, I forgot one transpose:

`A' * B = C`, but `B' * A = C'`

### CODE REVIEW

**Comment by arrufat** [comment]
I am running the example again. Hopefully, it will only perform better.
I will update the accuracy results in the example if they change.

**Comment by arrufat** [comment]
Regarding the build error on macOS, It seems we will have to update to Pybind11 v2.10.1. From their changelog: "_This is the first version to fully support embedding the newly released Python 3.11._"

However, I am surprised that macOS on GitHub actions is already using Python 3.11.

**Comment by arrufat** [comment]
The results didn't change, but I have peace of mind now.

**Comment by arrufat** [comment]
Hmm, somehow the tests pass again...

**Comment by davisking** [comment]
Huh. Yeah Mac OS cloud environments have never been super reliable for me. I wouldn't worry about it.

**Pull request merged**
