### PR TITLE
Added static_cast and additional braces to fix compilation warnings.

### PR DESCRIPTION
**Pull request by YuriiOlenych**

### CODE REVIEW

**Comment by davisking** [comment]
Thanks for the PR.  

The static_casts are fine, but those extra {} are bizarre.  What compiler generates a warning for code like array<int> a = {1,2,3}; and requires you to double up the {} to make the warning go away?  What is the warning?

**Comment by YuriiOlenych** [comment]
Warning: "suggest braces around initialization of subobject [-Wmissing-braces]".
Please take a look at the example in https://en.cppreference.com/w/cpp/container/array.

**Comment by davisking** [comment]
That page shows = using just {}, not {{}}.

**Comment by YuriiOlenych** [comment]
`std::array<int, 3> a1{ {1, 2, 3} }; // double-braces required in C++11 (not in C++14)`

**Comment by davisking** [comment]
Yes, but that's not what's in the PR.

**Comment by davisking** [comment]
Yes.  It's most definitely legal to say things like `std::array<int, 3> a = {1,2,3};`.

**Comment by davisking** [comment]
This honestly seems like a compiler bug.

**Comment by YuriiOlenych** [comment]
Yeah, probably. Found this: https://stackoverflow.com/questions/31555584/why-is-clang-warning-suggest-braces-around-initialization-of-subobject-wmis
But still, in our project, we are treating all warning as errors.

**Comment by davisking** [comment]
Yeah, what can you do :)

**Pull request merged**
