### PR TITLE
Silence warning about unused variable

### PR DESCRIPTION
**Pull request by arrufat**
I was getting a warning about this.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
We probably need one of the github actions workflows to build dlib with `DLIB_ASSERT` enabled

**Comment by arrufat** [comment]
Oh, right, I have my text editor to highlight all references of variables, and since that macro is disabled, I saw nothing. Sorry about that. How can we silence the warning, though? Move it to `DLIB_CASSERT`?

**Comment by pfeatherstone** [comment]
I would instead just add ```(void)imgsize;```

**Comment by pfeatherstone** [comment]
Or add `std::ignore = imgsize`

**Comment by davisking** [comment]
> We probably need one of the github actions workflows to build dlib with `DLIB_ASSERT` enabled

I've got one of the windows builds doing a debug build to at least make sure they compile.  Could have another one in linux.  Trying to not have a huge number of things running since it takes a while.

**Comment by davisking** [comment]
Thanks for the PR :)

**Pull request merged**
