### PR TITLE
Made probability weighting in gibbs sampler dependent on parents prob…

### PR DESCRIPTION
**Pull request by okirmis**
…abilities instead of the children's

To be honest, I'm not 100% sure, but I think it makes more sense to use the parent nodes' probabilities for weighting the result as they values are used to look up the probability for the current node in the probability table.

Please correct me if I am wrong as I use this modified version for a university project.

### CODE REVIEW

**Comment by davisking** [comment]
Why would this be the right thing to do?  Also, it breaks the bayesian network unit tests and causes the Gibbs sampler to produce the wrong outputs.

**Comment by okirmis** [comment]
As I said, I am not 100% sure about this. But why do we multiply it with the probability of the children when we want to create a probability for the node's state which depends on its parents' states?

What tool did you use to calculate the results you compare the the output to in the unit test? I'd like to give it a try.

**Comment by davisking** [comment]
The calculation depends on the parents as well as the children, the why is complicated.  You should google bayesian networks and read about d-separation.  I calculated the correct value with the junction tree algorithm.

**Comment by okirmis** [comment]
Yes, as written in the "Edit" section, the source I used for the algorithm was updated an the error was fixed. The PDF I linked there also describes it like you implemented it.

**Pull request closed without merging**
