### PR TITLE
Remove vscode stuff

### PR DESCRIPTION
**Pull request by arrufat**

### CODE REVIEW

**Comment by davisking** [comment]
Yeah saw that go in.  I have mixed feelings about it.  If it's really for real super annoying to not have it it can be there. But better to not have it.  I figured @Cydral really wanted it since it was in several PRs :)   

In any case, I can be talked into putting it back if it's really worth it.  It does seem like user settings ought to be able to be elsewhere though.  I use vim and not vscode though so I don't have perspective on it.

**Comment by arrufat** [comment]
Yeah, I don't use vs code either, but I figured that this kind of config should be personal. I'm not even sure about what those settings do.

**Comment by Cydral** [comment]
On my end, I don't need it; I guess it's added automatically when I use the editor directly on GitHub...

**Comment by arrufat** [comment]
What's surprising is that .gitignore contains a pattern for it.

**Pull request merged**
