### PR TITLE
Fix #1849 by calling device_global_buffer() unconditionally

### LINKED ISSUE #1849: Semantic Segmentation example crashes with multiple GPUs and loss increase
Hi, I'm using dlib from latest git revision and the semantic segmentation example crashes when used with multiple GPUs and the loss increases, so the trainer reloads from a previous state.
I suspect this might be related to https://github.com/davisking/dlib/issues/1677.
As with that issue, the only modification I made to the example code was adding the GPU initializer list to the `dnn_trainer`.

Here's the exact error:
```
step#: 64369  learning rate: 0.1   average loss: 0.424571     steps without apparent progress: 7989
Loss has been increasing, reloading saved state from pascal_voc2012_trainer_state_file.dat_
An unhandled exception was inside a dlib::thread_pool when it was destructed.
It's what string is: 
Error while calling cudaMemset(loss_cuda_work_buffer, 0, sizeof(float)) in file ../dlib/cuda/cuda_dlib.cu:1676. code: 11, reason: invalid argument
```

I suspect this might be hard to reproduce on other people's machines, but I have saved the state files when reloaded from makes this happen, so if you come up with a fix, I can try it easily.

Thanks in advance.

### PR DESCRIPTION
**Pull request by reunanen**
Also made `buf` a member variable.

### CODE REVIEW

**Comment by davisking** [comment]
Sweet, thanks for fixing this :)

**Comment by davisking** [comment]
This whole thing has mad me realize the device global buffer API was too complex and error prone. I just pushed a diff that makes it a lot simpler.  Now you just do:
```
cuda_data_void_pointer buf = device_global_buffer(size);
```
I tested everything locally and it seems fine. Can you grab the latest dlib and use that in your testing as well?  

In retrospect, I'm not sure why I didn't write it this way in the first place :|

**Comment by reunanen** [comment]
Yeah, even the latest master works on my test machine (2 * GTX 1080 (non-Ti)).
(At least in this respect. Didn't test anything else for the time being.)

**Comment by davisking** [comment]
Sweet

**Pull request merged**
