### PR TITLE
[SERIALIZATION] added support for std::variant

### PR DESCRIPTION
**Pull request by pfeatherstone**
Does what it says on the tin.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
I could add std::optional to this PR. That's pretty trivial and would complete the extra c++17 containers I think. (std::any is impossible to serialise/deserialise in a portable way)

**Comment by davisking** [comment]
I'm not sure this is a super good idea.  Like I would in general expect people to sometimes add or remove types from a variant.  But once you have started saving an object out via serialize you often need to maintain the ability to load old serialized data in later.  But the setup here makes that impossible, since there is no way for someone to load in an old variant that has a different set of types in it.

So I think this is something users should do on their own.  And hopefully when they do it, if they think they could ever possibly care about this kind of backwards compatibility, they will add version information or something (there are lots of options) so their serialization code to accommodate supporting loading old data.  But if it's in dlib then it's basically immutable for users, which isn't great in this specific instance.

**Comment by pfeatherstone** [comment]
Can't we just add a version number? 
Also i see no reason why we can't serialize ```std::variant```, but we can ```dlib::type_safe_union```

**Comment by pfeatherstone** [comment]
OK i see your point. But you could argue type versioning for any type, even ```float```. I could argue the way you save ```float``` is not how I would save ```float```, but i work with how dlib saves ```float```.

**Comment by pfeatherstone** [comment]
With regards to adding and removing types, you can also do that with ```std::tuple``` using ```std::tuple_cat```, yet we support serializing ```std::tuple```. It sounds like what you describe is something 1 or 2 users have done and having a built-in serializer for ```std::variant``` would break their code. I think if you're going to do something wacky like add and remove types from ```std::variant``` and still want serialization to work in a backwards compatible way, then call your serializer something different, like ```void serialize_variant_special(const std::variant<...>& item, std::ostream& out)```

**Comment by davisking** [comment]
Yeah, you are right. We should have this and it’s on the user to layer whatever versioning they might need around it in some outer type. 

Can you make it not require the type be movable though?

**Comment by pfeatherstone** [comment]
Yes sure. Do you have an opinion on how to do that? 
I think the compromise is that the type needs to be default constructible.

**Comment by pfeatherstone** [comment]
And it might need to be swappable.

**Comment by pfeatherstone** [comment]
@davisking OK, i think the only requirement is that the type be default constructible. :)

**Comment by davisking** [comment]
Yep, looks good :)

**Comment by pfeatherstone** [comment]
Ready

**Pull request merged**
