### PR TITLE
Added bind_front() and bind_back()

### PR DESCRIPTION
**Pull request by pfeatherstone**
Hopefully it is fully constexpr and conditionally noexcept with C++14 onwards

### CODE REVIEW

**Comment by pfeatherstone** [comment]
Could add bind_back() as well. Though I've never had a need for it.

**Comment by pfeatherstone** [comment]
@davisking This should be ready to go

**Comment by davisking** [comment]
I'm getting a build error for this when trying it with gcc 7.5.0.  Try building with that and you will see what I mean.

**Comment by pfeatherstone** [comment]
Cool. I'm currently using Ubuntu22 so will figure out a way to install gcc7

**Comment by pfeatherstone** [comment]
Might have to get a rusty old RPI out. I think gcc7 is the default ok raspbian

**Comment by pfeatherstone** [comment]
I think this will work. But this is definitely due to a bug in gcc7. I've seen other similar reports online

**Comment by davisking** [comment]
Yeah.  Totally a bug in that version of gcc.

Anyway, thanks for the PR :)

**Pull request merged**
