### PR TITLE
Add support for loading custom label fonts in imglab

### LINKED ISSUE #2732: I want to know how to support unicode character in box label in imglab. Could you give me some hints. Thanks!
I want to know how to support unicode character(for example:标签) in box label in imglab. Could you give me some hints. Thanks!

### PR DESCRIPTION
**Pull request by arrufat**
Closes #2732

### CODE REVIEW

**Comment by pfeatherstone** [comment]
Weird how Github Actions can sometimes cancel a job for no reason.

**Comment by davisking** [comment]
Nice, thanks :)

**Comment by arrufat** [comment]
Oh I wasn't expecting for this to get merged before getting some feedback from who reported the issue.

I couldn't test it properly, because copy and paste don't work well with Wayland in the dlib toolkit.

The font is changed though, but I might need to handle the UTF-8 strings when loading the dataset...

I will do that tonight, probably.

**Comment by davisking** [comment]
Ah ok. Well still looks like a sensible thing to have in any event 🤷‍♂️😁

**Comment by arrufat** [comment]
I've started working on that, and I can get imglab to load the Chinese characters from the XML files, just by changing:

```diff
diff --git a/tools/imglab/src/metadata_editor.cpp b/tools/imglab/src/metadata_editor.cpp
index f3e0e49d..c7e59cf1 100644
--- a/tools/imglab/src/metadata_editor.cpp
+++ b/tools/imglab/src/metadata_editor.cpp
@@ -656,9 +656,13 @@ on_overlay_rect_selected(
     const image_display::overlay_rect& orect
 )
 {

-    overlay_label.set_text(orect.label);
+    overlay_label.set_text(convert_utf8_to_utf32(orect.label));
     display.set_default_overlay_rect_label(orect.label);
     display.set_default_overlay_rect_color(string_to_color(orect.label));
}
```

However, I can't get the overlay rectangle to display them properly...
Maybe its `label` field needs to be a `dlib::ustring`? But that would be a breaking change.

**Comment by davisking** [comment]
Yeah `draw_string()`, called in `image_display::draw()`, needs to get a `ustring` or it's just drawing ASCII.  `image_display` should probably just interpret the `label` as utf8 always.  I'm not sure where the conversion to `ustring` should live though.  Could be in `draw_string()` but IDK, that adds a memory allocation on every call along with the conversion and that will end up making the UI laggy sometimes.  Not this UI probably, since there isn't a lot of text, but others I would expect.

Although the code in `convert_utf8_to_utf32()` could be refactored into a function like this:
```
convert_utf8_to_utf32(some_utf8_string.begin(), some_utf8_string.end(), [](unichar ch) {
   visits the unicode characters in order.
});
```
That could be done without memory allocations and then `draw_string()` could use that and everything would just work with utf8 all the time.

**Comment by arrufat** [comment]
Ah, after adding `convert_utf8_to_utf32()()` all over the place in `image::display::draw()`, everything works.

However, I can't see how we can make `convert_utf8_to_utf32()` allocation free, `some_utf8_string.size()` ≤ `some_utf32_string.size()`, right?

Maybe I am fundamentally wrong, I have a very shallow understanding about character encoding…

**Comment by davisking** [comment]
> convert_utf8_to_utf32

Yeah that function as is can't be allocation free.  A function like this could be:
```
convert_utf8_to_utf32(some_utf8_string.begin(), some_utf8_string.end(), [](unichar ch) {
   visits the unicode characters in order.
});
```
Just needs to use something other than that `istringstream` to iterate over the input string and then instead of appending characters to that new string it would call the provided lambda.

**Comment by arrufat** [comment]
At the risk of souding a bit dumb, it's not clear to me where the output uttf-32 string would be stored :sweat_smile:

**Comment by arrufat** [comment]
I will give it a go later (still not sure I am understanding this correctly, maybe it's too late in here)

**Pull request merged**
