### PR TITLE
Changed directory of license

### PR DESCRIPTION
**Pull request by meSajied**
As LICENSE.txt was in another directory, Github was not showing up the license when entered in the repository. This will confuse open-source contributors that this is a open-source library or free library. That is why I think license should be in root directory although mentioned in the readme.

### CODE REVIEW

**Comment by davisking** [comment]
Sure, but fix the link address and copy, don't move the license.

**Comment by meSajied** [comment]
should I create a symbolic link to root?

**Comment by davisking** [comment]
Just a copy.

**Comment by meSajied** [comment]
do you mean I should make a copy in root and change the link, but not to move that one?

**Comment by meSajied** [comment]
@davisking 
do I need any other changes?

**Review by davisking — COMMENTED** [review]
Looks good.

**Pull request merged**
