### PR TITLE
Added set_dnn_prefer_smallest_algorithms()

### PR DESCRIPTION
**Pull request by HarveyBrezinaConniffe**
I added a python binding for the set_dnn_prefer_smallest_algorithms() function!

### CODE REVIEW

**Comment by davisking** [comment]
Cool, thanks for the PR :)

Looks good.  Just add a doc string to the function and it's ready to merge.

**Comment by HarveyBrezinaConniffe** [comment]
Just did that!

**Comment by davisking** [comment]
Cool.  Change the word architectures to algorithms :)

**Comment by davisking** [comment]
Looks good. Thanks for the PR :)

**Comment by HarveyBrezinaConniffe** [comment]
Thanks, Seems to have fixed the problems I was having, I closed the issue as well!

**Pull request merged**
