### PR TITLE
Resolve davisking/dlib#2463

### PR DESCRIPTION
**Pull request by sambhare**
Fixes missing ssize_t definition on Windows

### CODE REVIEW

**Comment by davisking** [comment]
Thanks for the PR.  This doesn't work though, see the build errors here https://ci.appveyor.com/project/davisking/dlib-1mqn9/build/job/dyfua7l48ii2gs9g.  I'm not sure why the appveyor integration says it passed, since the build failed on appveyor :|

The issue is sometimes ssize_t is defined.

**Comment by sambhare** [comment]
Interesting. Looks like the 32 bit builds are failing and the 64 bit ones are ok. I'll update the PR to only do this on 64 bit.

Also, Python 3.6 was EOLed in Dec 2021. (https://devguide.python.org/#status-of-python-branches) Would you be updating your CI to remove it? I would recommend the oldest supported version (3.7) and the latest version (3.10)

**Comment by davisking** [comment]
Yeah, I'll update the appveyor config.  I tried 3.10 a bit ago but seemingly appveyor doesn't actually support it, despite their docs saying they do.  Trying to switch to 3.9 instead.

Anyway, thanks for the PR.  CI looks good now :)

**Comment by sambhare** [comment]
Thank you!

**Pull request merged**
