### PR TITLE
[SERIALIZATION] updated vectostream_abstract

### PR DESCRIPTION
**Pull request by pfeatherstone**
@davisking Sorry i didn't do this in the last PR.

### CODE REVIEW

**Comment by davisking** [comment]
No worries, thanks for the PR :)

I thought about how this was missing early in the PR but by the time I got to merging it forgot about it too so ¯\_(ツ)_/¯

**Comment by pfeatherstone** [comment]
@davisking Would you also be interested in enhancing ```dlib::vectorstream``` to support ```std::shared_ptr<char>``` (and int8_t, uint8_t) as the underlying buffer with some additional code for wrapping said buffer, carefully resizing it, etc? I have a use case where i need to serialize to ```shared_ptr<char>```, and again i have 2MB of RAM. So minimal copies and memory allocations is a priority. Now i could just serialize to ```vector<char>``` then copy at the end. That would maybe work and hopefully i wouldn't run into an "out of memory" exception. But just wondering if other people would have a need to serialize to ```shared_ptr<char>``` too, in which case adding this functionality could be useful. 

Here is an example of what i mean:

[vectorstream.h.txt](https://github.com/davisking/dlib/files/5980910/vectorstream.h.txt)

**Comment by davisking** [comment]
Can't you use `ostrstream` for this then?  That's basically what it is https://en.cppreference.com/w/cpp/io/ostrstream.  It's deprecated but I have a feeling it's never actually going away.  But it's deprecated because this kind of API is pretty easy for users to screw up.

**Comment by pfeatherstone** [comment]
Erh, that's the first time i've ever seen something deprecated in C++. Hmm, maybe i could use it. I've submitted another PR that gives you an idea of what i had in mind. I'm still not sure how i feel about it.

**Pull request merged**
