### PR TITLE
Fix for #2729

### PR DESCRIPTION
**Pull request by pfeatherstone**

### CODE REVIEW

**Comment by pfeatherstone** [comment]
I messed up and committed to master. Oh well

**Comment by davisking** [comment]
Sweet, thanks :)

**Comment by pfeatherstone** [comment]
This is why open sourcing stuff is a good idea. People spot bugs you were never going to find and could one day cause you a world of pain. It gets more mature quicker and benefits me greatly. Basically users become free testers.

**Comment by davisking** [comment]
Indeed :)

**Pull request merged**
