### PR TITLE
generic_image leftovers fix

### PR DESCRIPTION
**Pull request by kino-dome**
Corrected some of the functions that should use generic_image interfaces but were calling member functions on input images

### CODE REVIEW

**Comment by kino-dome** [comment]
Hi Davis! Sorry to bother you but I wanted to see if you will be merging this PR anytime soon? I need this merged to be able to release my dlib-dependant work. Thanks

**Comment by davisking** [comment]
The unit tests are failing to build.  You need to fix that first.  It should be displaying that to you on the PR page.  You don't see the box with the red letters "All checks have failed"?

**Comment by kino-dome** [comment]
Actually this was my first PR ever on github, so I need to apologize for the noobness of my request :) will correct the problem and do another PR

**Comment by davisking** [comment]
No worries :)

**Pull request closed without merging**
