### PR TITLE
Python: Add grayscale overloads to get_face_chip

### LINKED ISSUE #2736: [Feature Request] Add grayscale support to `dlib.get_face_chip()`
I found that using the detector and predictor on images converted to grayscale (`grayscale = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)`), is significantly faster. 

It greatly increases code complexity to carry around a color image only for `dlib.get_face_chip()` and convert back to grayscale afterwards, if running a detection and landmarking again on the returned chip.

### PR DESCRIPTION
**Pull request by arrufat**
Closes #2736.

### CODE REVIEW

**Comment by arrufat** [comment]
@mcp292, can you check if that works for you?

**Comment by mcp292** [comment]
This is awesome. Thank you both very much!

What release is this scheduled for?

**Comment by davisking** [comment]
Uh yeah.  I should really make dlib v19.25.  I need to go over the docs and square it all away and push it up.  I'll get around to it, maybe this weekend.  We will see :)

**Comment by mcp292** [comment]
Sounds good!

**Pull request merged**
