### PR TITLE
Update widgets and draw_string on images to use convert_to_utf32

### PR DESCRIPTION
**Pull request by arrufat**
Oops, I missed these, sorry :(

### CODE REVIEW

**Comment by arrufat** [comment]
Do you think we should template all those methods to be:
```c++
template <typename char_type, typename traits, typename alloc>
set_text (
    const std::basic_string<char_type, traits, alloc>& text
)
{
    set_text(convert_to_utf32(text));
}
```

**Comment by davisking** [comment]
No worries, thanks for the PR :D

**Comment by davisking** [comment]
> Do you think we should template all those methods to be:
> 
> ```c++
> template <typename char_type, typename traits, typename alloc>
> set_text (
>     const std::basic_string<char_type, traits, alloc>& text
> )
> {
>     set_text(convert_to_utf32(text));
> }
> ```

Na.  I've never seen anyone need that for `std::basic_string`.  So I would wait for the need to arise.

**Comment by arrufat** [comment]
I just noticed I didn't add `convert_to_utf32` to `draw_string` for images. So, I am adding it here, too.

I really like how I now don't need to care if my string has non ASCII characters and call `convert_utf8_to_utf32` like before. Now dlib does the right thing automatically.

Thank you for guiding me on how to achieve the allocation-free conversion :)

**Comment by davisking** [comment]
> I just noticed I didn't add `convert_to_utf32` to `draw_string` for images. So, I am adding it here, too.
> 
> I really like how I now don't need to care if my string has non ASCII characters and call `convert_utf8_to_utf32` like before. Now dlib does the right thing automatically.
> 
> Thank you for guiding me on how to achieve the allocation-free conversion :)

My pleasure :D

**Pull request merged**
