### PR TITLE
Fixes issue with object named nil that collide with apple's definition.

### PR DESCRIPTION
**Pull request by roymacdonald**
Fixes issue https://github.com/davisking/dlib/issues/536

### CODE REVIEW

**Comment by davisking** [comment]
Cool, thanks for the PR.  Can you make the change to a variable that has the same meaning as nil.  num_nodes isn't a sensible name for that variable in the min cut code.  Something like no_parent would be much better.

**Comment by roymacdonald** [comment]
Hi. Sure. No problem.
I used num_nodes as the variable was assigned with the number of nodes.
I'll fix it asap.

**Comment by roymacdonald** [comment]
@davisking done. 
Are the other var names I chose fine?
BTW, dlib is superb. Awesome work you've done. :D 
best

**Comment by davisking** [comment]
Those all look good.

Thanks, glad you like dlib :)

**Comment by roymacdonald** [comment]
super!
Thanks.
cannot think anything else than "the internet is awesome." :D

**Pull request merged**
