### PR TITLE
Find Threads target if necessary (#2522)

### PR DESCRIPTION
**Pull request by APTX**
While I am not a cmake expert (and certainly not camke 2.x) I thought I'd give it a go.

### CODE REVIEW

**Comment by davisking** [comment]
Thanks for the fix :)

**Comment by APTX** [comment]
No problem.

I am not sure the checks actually test this issue. As far as I can tell, nothing actually uses the cmake config. The builds also don't seem to use CUDA, where the `Threads` dependency comes from.

**Comment by davisking** [comment]
Heh, wait, but doesn't this change fix the problem for you?

**Comment by davisking** [comment]
Or are you talking just about the github CI checks?  Yeah those aren't exercising the problem you are fixing here.

**Comment by APTX** [comment]
The change does fix the problem for me. I was talking about github CI.

**Pull request merged**
