### PR TITLE
generic_image all the way

### PR DESCRIPTION
**Pull request by kino-dome**
tried to hunt down and correct the functions that were using a
non-generic_image approach to dlib’s generic images.
Hope it's ok this time, thanks :)

### CODE REVIEW

**Comment by davisking** [comment]
There are instructions on the front page for how to run the unit tests: https://github.com/davisking/dlib.  So you can do that if you need to find the errors.  

You can also modify your existing PR, you don't have to resubmit it.  Although you can if you want.  But git lets you make a bunch of commits against your PR.

**Comment by kino-dome** [comment]
Ok, thanks for the info. Will do the checks properly this time

**Comment by davisking** [comment]
Huh, that windows build failure seems to be because of something I recently changed.  Oddly, I didn't get a build failure for it until this PR.

**Comment by davisking** [comment]
Looks good.  Thanks for the PR :)

**Comment by kino-dome** [comment]
Yeah was trying to wrap my head around how that happened. Happy it wasn't me :) Cheers!

**Comment by davisking** [comment]
Yeah, just a bug in visual studio :(

**Pull request merged**
