### PR TITLE
Add cmake files for android build

### PR DESCRIPTION
**Pull request by lilac**
Borrow cmake files from opencv, to make it buildable using Android's ndk toolchain.

### CODE REVIEW

**Comment by davisking** [comment]
Have these files been adapted to dlib in some way?  Or are they simply copies of files from another project?

**Comment by lilac** [comment]
@davisking They are copied from https://github.com/taka-no-me/android-cmake but I verified that it works without problems. I actually did not modify any of those files.

**Comment by lilac** [comment]
If you think that's no worth to be copied to this project. Feel free to close it.

**Comment by davisking** [comment]
Yeah, people who want to use it can just get it from the original project :)

**Comment by lilac** [comment]
But there is no any documentation about that. Having it checkin have the benefits or supporting more platform without much effort.
If not added, I wish there is a documentation about this somewhere. That would save others' time.

**Comment by davisking** [comment]
That's true.  But copying the files doesn't address the lack of
documentation.  If you wrote a blog post or something like that which
documented how to setup an android build using cmake that would be super.

**Pull request closed without merging**
