### PR TITLE
Build ancillary tools on Windows

### PR DESCRIPTION
**Pull request by arrufat**
Let's see if this works

### CODE REVIEW

**Comment by davisking** [comment]
Cool, thanks :)

**Comment by arrufat** [comment]
Maybe we could build all the examples, except for the dnn ones? That should not cause an OOM exception.

**Comment by davisking** [comment]
Yeah, that's kinda unsatisfying too though.  Needs to be all of them or we need to keep using appveyor.  Maybe there is some way to get more ram on github actions.

**Comment by davisking** [comment]
Kinda seems like that's not an option. Maybe building in debug mode uses less ram though?

**Comment by davisking** [comment]
Don't worry about it.  I just pushed a commit that does it. :)

**Comment by davisking** [comment]
It's worth having a debug only build anyway since it tests codes in the `ENABLE_ASSERTS` pathways.  My server in the basement tests that stuff.  I would go crazy and add all kinds of stuff but I don't want tests to take forever or get rate limited by github like we did on travis.  Maybe that won't happen though.  But I bet at some point they are like "knock it off" if we run too much stuff.

**Comment by arrufat** [comment]
Oh, I see. Yes, I remember you having to remove some tests because we ran out of quota. And also tests taking over than 1 hour to start on Appveyor.
The good thing about GitHub actions is that they run pretty quickly.

**Comment by davisking** [comment]
Yeah seems to be a ton of quota on github.  Travis doesn't even run anymore.  We are constantly out of quota.

**Comment by arrufat** [comment]
Oh, same problem, when building the YOLO example:
```
   dnn_yolo_train_ex.cpp
D:\a\dlib\dlib\dlib\dnn\core.h(1102,1): fatal error C1060: compiler is out of heap space [D:\a\dlib\dlib\dlib\test\build\examples\examples_build\dnn_yolo_train_ex.vcxproj]
```

**Comment by davisking** [comment]
Yeah, debug build doesn't help :|

**Comment by arrufat** [comment]
From what I've seen, only the YOLO and the Semantic segmentation examples cause an OOM problem…

**Comment by davisking** [comment]
Yeah, same.

**Pull request merged**
