### PR TITLE
FFT: added std::vector overloads for fft, ifft, fft_inplace and ifft_inplace

### PR DESCRIPTION
**Pull request by pfeatherstone**
This is ready.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
@davisking In case you hadn't spotted this. This is ready for review/merge.

**Comment by davisking** [comment]
> @davisking In case you hadn't spotted this. This is ready for review/merge.

 Nice. I’ll take a look in a bit.

**Comment by davisking** [comment]
Looks good, thanks for another PR.  Just update the _abstract.h doc file to note these overloads and it's all good to go.

**Comment by pfeatherstone** [comment]
> Looks good, thanks for another PR. Just update the _abstract.h doc file to note these overloads and it's all good to go.

In the last FFT PR, you mentioned that the _abstract.h file didn't require mentioning overloads.

**Comment by pfeatherstone** [comment]
Or is it because, this time, the overloads aren't matrix-like?

**Comment by davisking** [comment]
The _abstract.h file is the user facing documentation.  So it's got to be
the case that someone can read that and only that and understand fully how
to use the API.  The other overloads were all just providing optimizations
for different kinds of matrices.  The API was just "give any dlib matrix".
The API supports all dlib matrix objects so also noting that "some sub-type
of matrix also has fft functions for it" doesn't tell the user something
new since they already know all matrices are supported. But with this PR
someone can also give a std::vector, a distinctly different type.  They
have to be able to find out this is possible by reading the docs.

Conversely, anything someone doesn't need to know to correctly use the API
should not be in the abstract file.

**Comment by pfeatherstone** [comment]
Got it. Thanks

**Comment by pfeatherstone** [comment]
@davisking Hopefully the abstracts are good now.

**Comment by davisking** [comment]
Looks good :)

**Pull request merged**
