### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by arrufat**
In https://github.com/davisking/dlib/pull/2285#issuecomment-761587077 I saw you said that it would be cool to test CUDA in dlib.

How would you feel about replacing Travis CI with GitHub Actions?

This PR adds a workflow that builds dlib with CUDA on several Ubuntu versions. I could add Windows and Mac support if you're interested

### CODE REVIEW

**Comment by arrufat** [comment]
I finally managed to get it working for Ubuntu with CUDA (some versions of CUDA reported incompatible driver version...)

**Comment by davisking** [comment]
> I finally managed to get it working for Ubuntu with CUDA (some versions of CUDA reported incompatible driver version...)

Sweet. No reason why we can't have appveyor, travis, and GitHub actions.   I didn't realize GitHub provided this, seems pretty nice. It would be cool to run all the unit tests on one service if it ends up being reliable and not a hassle.  Although, at the same time travis and appveyor have been solid for a long time.  So I'm inclined to leave them alone and just run the cuda stuff on actions.

**Comment by arrufat** [comment]
Good, so I will try to make it work for windows CUDA as well soon. And won't add CPU test versions, as they're already done by Travis (we can always add them later)

**Comment by pfeatherstone** [comment]
Just being a bit nosy. Having a quick look, it looks like you can setup Github actions to download, build and install dependencies. So i think in principle you could also run unit tests that have dependencies. Things that come to mind are MKL and libavformat (when i eventually get round to finishing the video_capture PR)

**Comment by arrufat** [comment]
> Just being a bit nosy. Having a quick look, it looks like you can setup Github actions to download, build and install dependencies. So i think in principle you could also run unit tests that have dependencies. Things that come to mind are MKL and libavformat (when i eventually get round to finishing the video_capture PR)

Yes, and this could also be to build the python wheel files for different CUDA/python versions

**Comment by arrufat** [comment]
I am not certain if I can add the Windows tests... I am not that familiar with Windows and how to install CUDA and CUDNN from the command line. Moreover, I don't have a Windows machine to test it...

Would you be ok to have a PR with only the Linux CUDA tests enabled? Maybe it will inspire someone with access to a Windows machine...

**Comment by davisking** [comment]
Yeah, doing stuff like this automatically in windows is frustrating since the normal install steps involve stuff like "A human touches a mouse and then...". Anyway, running CUDA tests on only linux totally fine and a pretty great improvement vs not having any automatic runs of them right now :)

**Comment by pfeatherstone** [comment]
`"A human touches a mouse and then..."`

I might use that on my next rant about windows.

**Comment by arrufat** [comment]
I don't know what's going on... Everything runs smoothly: setup, CUDA installation, dlib configuration with CUDA, dlib compilation of all the tests, but I get an error when I try to run `dtest --runall -q`...

You can see here the commands at the top (in blue) and their respective outputs below:
image

**Comment by arrufat** [comment]
Oh, apparently, the CUDA driver version in the docker host does not match the version in the container...
```
Failure message from test: Error while calling cudaGetDevice(&dev) in file /home/runner/work/dlib/dlib/dlib/cuda/cuda_dlib.cu:28. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
```

Not sure I can do something about it...

I tried installing the nvidia-drivers, but then I get different errors:

```
Failure message from test: Error while calling curandCreateGenerator(&gen, CURAND_RNG_PSEUDO_DEFAULT) in file /home/runner/work/dlib/dlib/dlib/cuda/curand_dlibapi.cpp:51. code: 203, reason: A call to cuRAND failed
```
Failure message from test: Error while calling cudaGetDevice(&the_device_id) in file /home/runner/work/dlib/dlib/dlib/cuda/gpu_data.cpp:204. code: 100, reason: no CUDA-capable device is detected
```

I have one extra idea, I hope it works...

```

**Comment by arrufat** [comment]
Oh, apparently, the CUDA driver version in the docker host does not match the version in the container...
```
Failure message from test: Error while calling cudaGetDevice(&dev) in file /home/runner/work/dlib/dlib/dlib/cuda/cuda_dlib.cu:28. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
```

Not sure I can do something about it...

I tried installing the nvidia-drivers, but then I get different errors:

```
Failure message from test: Error while calling curandCreateGenerator(&gen, CURAND_RNG_PSEUDO_DEFAULT) in file /home/runner/work/dlib/dlib/dlib/cuda/curand_dlibapi.cpp:51. code: 203, reason: A call to cuRAND failed
```

```
Failure message from test: Error while calling cudaGetDevice(&the_device_id) in file /home/runner/work/dlib/dlib/dlib/cuda/gpu_data.cpp:204. code: 100, reason: no CUDA-capable device is detected
```

I have one extra idea, I hope it works...

**Comment by arrufat** [comment]
I am running out of ideas... :(

**Comment by arrufat** [comment]
I might give it another go some other time...

**Comment by davisking** [comment]
Heh, wasn't paying attention.  You want me to pin this so the bot doesn't close it @arrufat?

**Comment by arrufat** [comment]
Ah, that would be good, it would make me not forget about this.
Everything works, (CUDA/CuDNN installation, dlib build and tests) but the GPU is somehow not detected... I wonder if that's because the system where it runs does not have an NVIDIA GPU... I need to look more into detail.

**Comment by arrufat** [comment]
I've added some simple workflows to build and run the tests, but apparently, it runs out of memory while building the examples…

**Comment by pfeatherstone** [comment]
Are those the DNN examples ?

**Comment by arrufat** [comment]
> Are those the DNN examples ? 

On Linux yes, on mac it built but one test failed. And on windows it's not clear for me. Apparently it built but returned an error...

**Comment by arrufat** [comment]
Aside from the macOS failing because the timer test doesn't pass, windows and linux builds work. I don't know what to do about macOS, though...

**Comment by arrufat** [comment]
After removing the timer test on macOS, all tests pass.
As you can see, it's really simple, maybe we can use this as a base script and improve upon it (add python builds, etc)

**Comment by arrufat** [comment]
I've just added a workflow to build the Python modules, and it works on the 3 OS. It's probably not as exhaustive as what you have on Travis now, though…

**Comment by davisking** [comment]
Sweet.  So how do we make this run live?  I haven't looked at github actions.  If I just merged this PR does github automatically look in that folder and just run them?  Or is there some other setup?

**Comment by arrufat** [comment]
I think it will run automatically once you merge it. The first lines in those yaml files define when they should run. It already runs automatically on my branch whenever I push :)

**Comment by davisking** [comment]
I would like to get off appveyor and travis.  Those platform are a pain.  Travis is fine, except we are always running out of quota.  And appveyor has a number of race conditions that make it unreliable in different ways.

**Comment by arrufat** [comment]
Yes, I saw that you were having problems with Travis, that's why I hurried to finish this PR

**Comment by arrufat** [comment]
I will probably work on CUDA testing in another PR.

**Comment by davisking** [comment]
Yeah, thanks for this :)

Let's merge it and see how it goes.

**Comment by davisking** [comment]
We might be able to get travis to work better.  I've emailed them a few times when we run out of quota. They always add more quota, but we just quickly run out again anyway so `¯\_(ツ)_/¯`

**Comment by arrufat** [comment]
Wow, it is way faster! At least in terms of starting a job once it's queued.

**Pull request merged**
