### PR TITLE
Make assignment from a mat(ptr,rows,cols) faster.

### PR DESCRIPTION
**Pull request by davisking**

### CODE REVIEW

**Comment by davisking** [comment]
Merged in https://github.com/davisking/dlib/pull/2822

**Comment by Compaile** [comment]
Quick question, why do we check for size!= 0 and that the stride fits the nc.
If we want to check the whole thing (which the second check suggest) should we not compare the whole size? instead of null check it.

And if thats for the user to check (which i dont think is dlibs philosophy) why do we check the second part at all?

**Comment by davisking** [comment]
> Quick question, why do we check for size!= 0 and that the stride fits the nc. If we want to check the whole thing (which the second check suggest) should we not compare the whole size? instead of null check it.
> 
> And if thats for the user to check (which i dont think is dlibs philosophy) why do we check the second part at all?

It's because `matrix_assign_default()` has these preconditions (from dlib/matrix/matrix_assign_fwd.h):
```
            - dest.nr() == src.nr()
            - dest.nc() == src.nc()
```
So we know the sizes match already.  We just have to determine when we can use what kind of memcpy() from there.

**Comment by Compaile** [comment]
ah perfect, thanks!

**Comment by davisking** [comment]
No problem :)

**Pull request closed without merging**
