### PR TITLE
Add Linux(x86_64 and aarch64) wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added Linux(x86_64 and aarch64) wheel build support.
Related to https://github.com/davisking/dlib/issues/2540, @davisking, Could you please review this PR?

### CODE REVIEW

**Comment by davisking** [comment]
Thanks for the PR.  What's this going to do?  Build the wheel and try to publish it to PyPi? Where is `secrets.PYPI_PASSWORD` coming from?

So `pip install dlib` should keep building the package.  People depend on that since it configures it for their system.  E.g. it detects CUDA and enables that if they have it.  It detects their CPU arch and enables AVX and/or SSE for instance, stuff like that.  That's all important.  But a generic binary has to disable all that stuff.  So it's not super clear to me that's really very useful to very many people.  Do you use dlib with all that stuff disabled?

**Comment by odidev** [comment]
> Thanks for the PR. What's this going to do? Build the wheel and try to publish it to PyPi? Where is `secrets.PYPI_PASSWORD` coming from?

secrets.PYPI_PASSWORD is the password you’ll need to set which allows you to upload your Python distribution packages in the dist/ directory to PyPI. 
For more information, please see this: https://docs.github.com/en/actions/security-guides/encrypted-secrets

> So `pip install dlib` should keep building the package. People depend on that since it configures it for their system. E.g. it detects CUDA and enables that if they have it. It detects their CPU arch and enables AVX and/or SSE for instance, stuff like that. That's all important. But a generic binary has to disable all that stuff. So it's not super clear to me that's really very useful to very many people. Do you use dlib with all that stuff disabled?

Wheels install faster than source distributions. Also it avoids arbitrary code execution (setup.py) for installation. For more information on wheels, please check this: https://pythonwheels.com/

**Comment by odidev** [comment]
@davisking, Any update on this?

**Comment by davisking** [comment]
We can't make `pip install dlib` disable the features I mentioned.  There could be a `pip install dlib-linux-binary-no-gpu-or-any-acceleration` I suppose, but I'm not super sure who would use that.

**Pull request closed without merging**
