### PR TITLE
Adding an install target to dlib's CMakeLists

### PR DESCRIPTION
**Pull request by severin-lemaignan**
This PR covers the first part of items discussed in #34, namely, the installation.

A follow-up PR (hopefully tomorrow) should cover the 2nd part, namely, the generation and installation of ``dlibConfig.cmake``

### CODE REVIEW

**Comment by mikeseven** [comment]
I'll piggy back on that one too.
I've some update for Windows MSVS and OpenBLAS config too. Once this is
pushed, I'll send my updates.

--mike

**Comment by davisking** [comment]
Some issues:
- I compiled the examples and now the dlib_build sub-folder contains a .so file that needs to exist for the executables to work.  If someone copies those executables somewhere else or deletes that folder then the executable stops working.  
- The dlib/config.h file needs to be modified by cmake to force the DLIB_ASSERT macros off and also to permanently set any other preprocessor macros used during build (e.g. DLIB_USE_BLAS, DLIB_USE_LAPACK, DLIB_PNG_SUPPORT, DLIB_HAVE_SSE4, etc.)
- I'm sure there is a way to read the version information out of a file rather than hard coding it in the cmake file (i.e. this one http://dlib.net/dlib/revision.h.html).

**Comment by mikeseven** [comment]
Thanks. I'll check that.
I only checked on windows and changed only windows section. Weird.

--mike

**Comment by severin-lemaignan** [comment]
@davisking I've added commits which address your concerns. The examples compile and statically link with dlib even in 'Release' mode.

For the version number, however, I would suggest to use CMake as the primary source of version numbers since it is very useful for CMake to generate packages/config files/etc.
Commit ff7a254 creates and configure a ``revision.h`` witth the correct revision number, but I did not hooked it in the doc generation mechanism (``makedocs``) -- not sure how to do that properly.

**Comment by severin-lemaignan** [comment]
The last commit, c9b1c4b, adds the generation and installation of ``dlibConfig.cmake`` and ``dlibConfigVersion.cmake``.
The ['official' way](http://www.cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-packages) of making ``xxxConfig.cmake`` is quite confusing, and my attempt is probably not good enough yet (in particular, setting the library with ``set(dlib_LIBRARIES dlib)`` is not correct: the linker won't find it is not installed in a standard location). Help welcome!

**Comment by davisking** [comment]
Yeah moving the version numbers into the CMakeLists.txt file does make sense.  Once this PR is finished I'll update the scripts and whatnot in docs to extract the version information from cmake rather than the current set of files.

A few more issues (only tested in cygwin so far):
- When I tried to build dlib I got this error: `CMake Error at CMakeLists.txt:434 (install): install Library TARGETS given no DESTINATION!`.  Changing the install call to this `install(TARGETS dlib-shared EXPORT dlib LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)` seems to fix it.
- When I compiled the examples via the usual `cd build; cmake ..; make` it now builds dlib two times, once for the shared library and once for the archive.  
- The examples also print `dlib is built in Release mode: you can install it with 'make install'` which shouldn't be printed in client cmake files.  Maybe the right way to do this whole thing is to have a folder somewhere, say `dlib/install`, that has a special CMakeLists.txt file in it which includes `dlib/cmake` but adds whatever is necessary to do a `make install`.  This way existing users are not troubled with the `make install` features we are talking about adding.
- Just being compiled in release mode should not disable asserts.  For example, I often do debugging with release mode and asserts enabled because I'm debugging some big computation and it takes forever if I run the code without optimizations.  So in this case I'll go into ccmake and turn on the asserts while in release mode.  What is important here for the installer is just that the dlib/config.h file permanently configures the asserts one way or another.  Probably the right thing is to have cmake tell dlib/config.h to set the asserts on/off based on the setting of the DLIB_ENABLE_ASSERTS option (which is defaulted to off in release mode).

Finally, when trying to run make on the makefile generated for building just the dlib folder I get a bunch of linker errors at the end that look like this:

Linking CXX shared library cygdlib.dll
CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b08): undefined reference to `XwcTextExtents'
CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b08): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `XwcTextExtents'
CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b43): undefined reference to `XFreeGC'
CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b43): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `XFreeGC'


Yeah, the cmake package documentation is a little confusing.  I've never set one up before though so I'm not sure how to do it :)

**Comment by severin-lemaignan** [comment]
> When I tried to build dlib I got this error: CMake Error at CMakeLists.txt:434 (install): install Library TARGETS given no DESTINATION!. Changing the install call to this install(TARGETS dlib-shared EXPORT dlib LIBRARY DESTINATION lib ARCHIVE DESTINATION lib) seems to fix it.

This I do not understand... I've updated the install target accordingly, though.

> When I compiled the examples via the usual cd build; cmake ..; make it now builds dlib two times, once for the shared library and once for the archive.

Yes, I'm not sure how to avoid it...

> The examples also print dlib is built in Release mode: you can install it with 'make install' which shouldn't be printed in client cmake files. Maybe the right way to do this whole thing is to have a folder somewhere, say dlib/install, that has a special CMakeLists.txt file in it which includes dlib/cmake but adds whatever is necessary to do a make install. This way existing users are not troubled with the make install features we are talking about adding.

I've removed the message altogether.

> Just being compiled in release mode should not disable asserts. For example, I often do debugging with release mode and asserts enabled because I'm debugging some big computation and it takes forever if I run the code without optimizations. So in this case I'll go into ccmake and turn on the asserts while in release mode. What is important here for the installer is just that the dlib/config.h file permanently configures the asserts one way or another. Probably the right thing is to have cmake tell dlib/config.h to set the asserts on/off based on the setting of the DLIB_ENABLE_ASSERTS option (which is defaulted to off in release mode).

This is fixed now: you can always enable or disable the asserts. Btw, you should probably prefix the ``ENABLE_ASSERTS`` macro with ``DLIB_`` to avoid possible macro collisions...

While here, I've also fixed my issue with detecting the library location: I've now been able to successfully compile and link with an installed ``dlib`` from an external project using the classical cmake workflow.

**Comment by severin-lemaignan** [comment]
> Linking CXX shared library cygdlib.dll
> CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b08): undefined reference to XwcTextExtents' CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b08): relocation truncated to fit: R_X86_64_PC32 against undefined symbolXwcTextExtents'
> CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b43): undefined reference to XFreeGC' CMakeFiles/dlib-shared.dir/gui_widgets/fonts.o:fonts.cpp:(.text+0x1b43): relocation truncated to fit: R_X86_64_PC32 against undefined symbolXFreeGC'

I've no idea about these linking issues... are you able to reproduce them on linux and/or macosx?

**Comment by davisking** [comment]
I just tried it on Ubuntu and don't get those linker errors.  Cygwin can be a fickle beast sometimes.  Don't worry about them for the moment.  The bigger issue is the double building since that doubles the build time of existing dlib projects.  But on the whole this PR is getting pretty good :)

Anyway, here is what I think you can do to fix the double building problem.  You should be able to set a variable in the dlib/cmake file that is something like `set(you_are_being_invoked_from_another_project_so_don't_make_the_shared_library 1)`.  You get the idea, but pick a more sensible variable name :).  Then make the install/shared lib building in dlib/CMakeLists.txt conditional on that variable.

Also, see if you can tell cmake to install not just the shared library but also the archive since we are building both and it's nice to include both when installed anyway.  I'm sure other users will ask for it as well.

As for renaming ENABLE_ASSERTS, yeah, you are right.  But it's too late to rename it now as that would break backwards compatibility.  If it were causing trouble then maybe, but no one has ever encountered problems with it so it's best to leave it alone.

Also, it's a good idea to include(release_build_by_default) (or do something similar) so that cmake will compile dlib with optimizations enabled.  Right now when you do the `cmake dlib; make install` it compiles it without any optimizations.

**Comment by severin-lemaignan** [comment]
> Anyway, here is what I think you can do to fix the double building problem. You should be able to set a variable in the dlib/cmake file that is something like set(you_are_being_invoked_from_another_project_so_don't_make_the_shared_library 1). You get the idea, but pick a more sensible variable name :). Then make the install/shared lib building in dlib/CMakeLists.txt conditional on that variable.

Done. Works well. The variable is named ``DLIB_IN_PROJECT_BUILD``.
 
> Also, see if you can tell cmake to install not just the shared library but also the archive since we are building both and it's nice to include both when installed anyway. I'm sure other users will ask for it as well.

Done
 
> Also, it's a good idea to include(release_build_by_default) (or do something similar) so that cmake will compile dlib with optimizations enabled. Right now when you do the cmake dlib; make install it compiles it without any optimizations.

I do not recommend doing it. Even if it looks convenient, it goes against the normal expectations (cmake projects are not supposed to set a preferred compilation type), and may likely disrupt/break packaging or other complex installation pipeline that may typically set compilation flags in the environment and do not expect individual packages to override this by default.

**Comment by severin-lemaignan** [comment]
While here, I don't know the official versioning policy of ``dlib``: I've put ``18.18`` in this PR, but ``18.17.99`` (or something alike) would be possibly better to clearly distinguish between released versions and development versions (I would personally favour this). Let me know if you wish I change it.

**Comment by davisking** [comment]
The dlib/release_build_by_default script should only set the cmake built type if it isn't already set by some other mechanism.  So I don't see how it would be disruptive to other packaging.  Or if it is then I have to imagine there is a straightforward way to fix the release_build_by_default script to only set the mode when it isn't disruptive.  Also, a huge number of users mess up and compile in some kind of optimized mode and then email me about it.  I litterally have a FAQ (http://dlib.net/faq.html#Whyisdlibslow) about it (and yes adding the red circle picture noticably reduces the number of questions I get which seems crazy but it's true).  

Setting the version number to 18.17.99 is a good idea.

**Comment by davisking** [comment]
Oops, meant to say "unoptimized mode".  But in any event, reducing user confusion is a worthy goal :)

**Comment by severin-lemaignan** [comment]
@davisking After looking a bit around, it seems it is actually an acceptable practice to set a non-null default configuration. [This thread](http://www.cmake.org/pipermail/cmake/2008-September/023808.html) has useful details on how to achieve that, and I've done so at the top of the ``CMakeLists.txt``. If this looks ok to you, we can then remove ``release_build_by_default``.

I've also update the version number to ``18.17.99``.

**Comment by davisking** [comment]
Nice, it looks good.  I'm going to test it on a few different platforms and see if I can find any issues :)

The only thing is I think you should use the dlib/release_build_by_default script instead of that if/else block.  In particular, I'm pretty sure the statement that sets CMAKE_BUILD_TYPE to itself is redundant.  And even if it isn't, having it in a script that can be included by other cmake scripts is convenient.  For example, dlib/cmake includes it and I know of other dlib users who include it in other unrelated cmake scripts to set the default build type.  So this way avoids duplication of cmake code.

**Comment by davisking** [comment]
I just tried it on cygwin and got those linker errors again.  However, the fix is easy, it's just to add a target_link_libraries() statement for dlib-shared as well as the dlib target.  That makes it compile.  However, when I do a make install it mostly works but it seems to only copy the static libraries to the output folder.  The .dll is compiled but not put into /usr/local/lib.  

The find_package(dlib) method of compiling does work in cygwin now that it's installed but running the produced executable doesn't work because the dll isn't in the right place.  Any ideas?

**Comment by davisking** [comment]
Also, shouldn't you take the RELEASE_MODE variable out of the cmake file entirely?  If someone wants to compile and install dlib in debug mode then they can go ahead and do that.

**Comment by severin-lemaignan** [comment]
> The find_package(dlib) method of compiling does work in cygwin now that it's installed but running the produced executable doesn't work because the dll isn't in the right place. Any ideas?

Can you add a ``message(STATUS "dlib libs: ${dlib_LIBRARIES}")`` to your external ``CMake`` script and check it finds something at least?

**Comment by severin-lemaignan** [comment]
> Also, shouldn't you take the RELEASE_MODE variable out of the cmake file entirely? If someone wants to compile and install dlib in debug mode then they can go ahead and do that.

What about renaming the variable to ``INSTALL_DLIB`` and make it a regular CMake option that would by ``ON`` by default on unixes in release mode, and ``OFF`` otherwise? would it do?

**Comment by severin-lemaignan** [comment]
Fixed the duplication of code (now using the ``release_build_by_default`` script) + added missing ``target_link_libraries``.

**Comment by davisking** [comment]
> What about renaming the variable to INSTALL_DLIB and make it a regular CMake option that would by  ON by default on unixes in release mode, and OFF otherwise? would it do?

But doesn't the DLIB_IN_PROJECT_BUILD solve all the issues INSTALL_DLIB solves?  I don't see why we need both.

**Comment by severin-lemaignan** [comment]
Hum... good point. So then, it simplifies into:
- ``DLIB_IN_PROJECT_BUILD`` is ``true``: we do not generate any install target whatsoever
- otherwise, we create an install target as would do any regular ``CMake`` project.

What about windows? should I also create an install target in that case? does it hurts?

**Comment by davisking** [comment]
On cygwin dlib_LIBRARIES is set to this: `/usr/local/lib/libdlib.dll.a;/usr/lib/libpthread.a;/usr/lib/libX11.dll.a;/opt/OpenBLAS/lib/libopenblas.a;gfortran` which is correct.  The build part works, it's just that `make install` doesn't put the dll file anywhere.  If I manually copy the missing dll from the build folder then the programs will run.

**Comment by davisking** [comment]
Yeah, that behavior for `DLIB_IN_PROJECT_BUILD` sounds good.  Probably letting someone run an install on windows is fine as long as find_package(dlib) works on windows. Projects like OpenCV do this and it works fine.  Or as fine as precompiling libraires ever works on windows which isn't great but there isn't anything we can do about that.

**Comment by severin-lemaignan** [comment]
> On cygwin dlib_LIBRARIES is set to this: /usr/local/lib/libdlib.dll.a;/usr/lib/libpthread.a;/usr/lib/libX11.dll.a;/opt/OpenBLAS/lib/libopenblas.a;gfortran which is correct. The build part works, it's just that make install doesn't put the dll file anywhere. If I manually copy the missing dll from the build folder then the programs will run.

Did you try to explicitely set a ``CMAKE_INSTALL_PREFIX``?

**Comment by severin-lemaignan** [comment]
I now always generate an install target, except for 'in project' builds. Seems to work well for me, and it indeed simplifies the whole thing.

**Comment by davisking** [comment]
Yeah, it doesn't make a difference. Only the .a and .dll.a files get installed. The .dll doesn't.

**Comment by severin-lemaignan** [comment]
Does [that](http://stackoverflow.com/questions/21592361/cmake-install-not-installing-libraries-on-windows) solves the issue?

**Comment by davisking** [comment]
Yeah that fixes it.  You want the `RUNTIME DESTINATION bin` version.  Yeah, the way shared libraries works on windows is [not so great](https://en.wikipedia.org/wiki/DLL_Hell).

**Comment by severin-lemaignan** [comment]
Alright, I've added ``RUNTIME DESTINATION bin``.

**Comment by davisking** [comment]
Cool, looks like it's working in cygwin.

I just remembered that visual studio doesn't output any linkable symbols by default.  So it basically doesn't generate a shared library.  You are supposed to put __declspec(dllexport) in front of every function and class to tell visual studio to export them.  But that is grotesque so I'm definitely not doing that.  Instead, I would suggest making the following changes to tell cmake to only output a static library when on windows (except for cygwin which is unix).  So add these changes:

--- a/dlib/CMakeLists.txt
+++ b/dlib/CMakeLists.txt
@@ -121,7 +121,7 @@ if (NOT TARGET dlib)

    if (DLIB_ISO_CPP_ONLY)
        add_library(dlib STATIC ${source_files} )
-       if (NOT DLIB_IN_PROJECT_BUILD)
+       if (UNIX AND NOT DLIB_IN_PROJECT_BUILD)
            add_library(dlib-shared SHARED ${source_files} )
        endif()
    else()
@@ -420,7 +420,7 @@ if (NOT TARGET dlib)
       add_library(dlib STATIC ${source_files} )
       target_link_libraries(dlib ${dlib_needed_libraries} )

-      if (NOT DLIB_IN_PROJECT_BUILD)
+      if (UNIX AND NOT DLIB_IN_PROJECT_BUILD)
           add_library(dlib-shared SHARED ${source_files} )
           target_link_libraries(dlib-shared ${dlib_needed_libraries} )
       endif()
@@ -429,14 +429,25 @@ if (NOT TARGET dlib)

    # Install the library
    if (NOT DLIB_IN_PROJECT_BUILD)
-       set_target_properties(dlib-shared PROPERTIES
-                                    OUTPUT_NAME dlib
-                                    VERSION ${VERSION})
-       install(TARGETS dlib dlib-shared
-               EXPORT dlib
-               LIBRARY DESTINATION lib
-               ARCHIVE DESTINATION lib)
-
+        if (UNIX)
+          set_target_properties(dlib-shared PROPERTIES
+                                OUTPUT_NAME dlib
+                                VERSION ${VERSION})
+          install(TARGETS dlib dlib-shared
+             EXPORT dlib
+             LIBRARY DESTINATION lib
+             ARCHIVE DESTINATION lib
+             RUNTIME DESTINATION bin
+             )
+       else()
+          install(TARGETS dlib
+             EXPORT dlib
+             LIBRARY DESTINATION lib
+             ARCHIVE DESTINATION lib
+             RUNTIME DESTINATION bin
+             )
+       endif()
+
        install(DIRECTORY ${CMAKE_SOURCE_DIR}/ DESTINATION include/dlib FILES_MATCHING PATTERN "*.h")




Also from playing around on windows with this it seems that some "" are needed here:
--- a/dlib/dlibConfig.cmake.in
+++ b/dlib/dlibConfig.cmake.in
@@ -36,4 +36,4 @@ if(NOT TARGET dlib-shared AND NOT dlib_BINARY_DIR)
 endif()

 find_library(dlib_LIBRARIES dlib HINTS ${dlib_INSTALL_PATH}/lib)
-set(dlib_LIBRARIES ${dlib_LIBRARIES} @dlib_needed_libraries@)
+set(dlib_LIBRARIES ${dlib_LIBRARIES} "@dlib_needed_libraries@")

**Comment by severin-lemaignan** [comment]
Could you please put your patch above between \`\`\`... it is pretty hard to read in the github interface :-)

**Comment by davisking** [comment]
I did.  It doesn't show up as between ``` for you?

**Comment by severin-lemaignan** [comment]
Not really :-)
screenshot from 2015-09-13 19-10-21

**Comment by severin-lemaignan** [comment]
> Also from playing around on windows with this it seems that some "" are needed

Done.

**Comment by davisking** [comment]
Weird.  Try refreshing the page a bunch.  I did post it wrong but edited it immediately which was about 2 hours ago.  This is what it looks like right now for me: 

github_weird

**Comment by severin-lemaignan** [comment]
Hum, interesting... looks ok for me now. Anyway...

**Comment by severin-lemaignan** [comment]
``cygwin`` enables the ``UNIX`` macro? otherwise, I need to make the install if/else a bit more clever.

**Comment by severin-lemaignan** [comment]
Ok, I've applied your change. Please let me know if it works as intended on cygwin and VS.

**Comment by davisking** [comment]
Yeah, cygwin enables UNIX.  cygwin basically pretends to be UNIX in most ways.  It's practically the opposite of the wine project.

**Comment by davisking** [comment]
Cool, will do.

**Comment by davisking** [comment]
I found some more things.  The configure_file statement for dlib/revision.h needs to be moved next to the other configure_file statement.  Otherwise cmake will generate revision.h files in odd places like in the examples folder when used for non-installing builds.

I also tried doing a build inside the source tree (i.e. `cd dlib;mkdir build; cmake ..`) and the current install statements copy files from within the build folder to the output when `make install` is run.  I also tried setting CMAKE_INSTALL_PREFIX=install which puts the output into the local install folder which in this case is inside the dlib source tree.  That causes `make install` to run forever because it keeps recursing into that install folder.  So something like cmake's EXCLUDE option should be used to prevent the CMAKE_BINARY_DIR from being output.

**Comment by severin-lemaignan** [comment]
> I found some more things. The configure_file statement for dlib/revision.h needs to be moved next to the other configure_file statement. Otherwise cmake will generate revision.h files in odd places like in the examples folder when used for non-installing builds.

Yes, I did it on purpose because it may be the case that some people want to rely on ``revision.h`` to test the version of ``dlib`` being used *also* when building by including ``dlib/cmake``. But if you think it is unlikely or that we do not to address this concern for now, I'll happily move ``configure_file`` further down.

**Comment by severin-lemaignan** [comment]
> I also tried doing a build inside the source tree (i.e. cd dlib;mkdir build; cmake ..) and the current install statements copy files from within the build folder to the output when make install is run. I also tried setting CMAKE_INSTALL_PREFIX=install which puts the output into the local install folder which in this case is inside the dlib source tree. That causes make install to run forever because it keeps recursing into that install folder. So something like cmake's EXCLUDE option should be used to prevent the CMAKE_BINARY_DIR from being output.

Fixed.

**Comment by severin-lemaignan** [comment]
Just to make sure I do understand correctly: ``simd`` optimizations are automatically enabled (by ``simd_check.h``) when available, right? so no need to expose options in the main ``CMakeLists.txt``, right? (then I guess ``SSE2``, ``SSE4`` and ``AVX`` flags are exposed in ``dlib/cmake`` just as a convenience for external project)

**Comment by davisking** [comment]
I doubt anyone who is pulling dlib from source control needs the revision.h file.  If they instead had downloaded the .tar.bz2 source distribution then the revision.h file will be there.  Also, cmake isn't putting it in the right folder all the time anyway :).  Not all dlib users use cmake as well.

Yeah, that's how simd_check.h works.  It's mainly there for visual studio since that compiler has an excessively complicated set of rules for how you turn SIMD instructions on and you can't tell if they are on via the preprocessor.  For gcc and clang it's simple and simd_check.h does all that is needed.  

I'll also look the code over a bit more to make sure nothing inside the dlib .cpp files is effected by the simd stuff.  If it is then there are possible ODR violations by not having these options in the dlib/CMakeLists.txt file.  However, I'm pretty sure the simd code doesn't touch anything in any .cpp files.  Moreover, even if it did I don't think we can require someone compiling on the command line like `g++ main.cpp -ldlib -mavx` to always remember to give the `-mavx`.  So it seems like the best thing to do is to make sure that compiling dlib's cpp files and the user's code using differing simd options is always ok and ODR violation free.  Like I said, I'm pretty sure that's the case now, but I'll look into it a bit more to make sure I remember correctly.

**Comment by severin-lemaignan** [comment]
> I doubt anyone who is pulling dlib from source control needs the revision.h file. If they instead had downloaded the .tar.bz2 source distribution then the revision.h file will be there. Also, cmake isn't putting it in the right folder all the time anyway :). Not all dlib users use cmake as well.

Ok, I've moved the configuration of `revision.h.in` to the build directory.

**Comment by severin-lemaignan** [comment]
@davisking Did you find time to thoroughly test the PR?

**Comment by davisking** [comment]
Not yet.  I've been busy the last week.  I'm planning on going through it this weekend though.

**Comment by davisking** [comment]
I think I've found all the remaining issues.  First, apparently find_package() on windows has the special behavior of searching recent build folders.  So if you build dlib somewhere and then try to compile the example programs with a CMakeLists.txt file that uses `find_package(dlib)` it fill find the dlibConfig.cmake file in your recent build folder and try to use it. But that results in an error on the line that says `    include("${dlib_CMAKE_DIR}/dlib.cmake")` since that isn't the right path.  I'm sure this error would confuse windows users so it should be addressed.  The best thing to do is probably to put the config files inside some sub-folder rather than right in the cmake binary dir, so find_package() won't see them.  

The only other remaining thing is to add the missing #define switches into config.h.  I.e. any #defines set by dlib/CMakeLists.txt need to be echoed into the config.h file.  So this includes DLIB_ENABLE_STACK_TRACE, DLIB_NO_GUI_SUPPORT, and DLIB_ISO_CPP_ONLY.

Other than those things I think the PR is ready :)

**Comment by severin-lemaignan** [comment]
> I think I've found all the remaining issues. First, apparently find_package() on windows has the special behavior of searching recent build folders. So if you build dlib somewhere and then try to compile the example programs with a CMakeLists.txt file that uses find_package(dlib) it will find the dlibConfig.cmake file in your recent build folder and try to use it. But that results in an error on the line that says include("${dlib_CMAKE_DIR}/dlib.cmake") since that isn't the right path. I'm sure this error would confuse windows users so it should be addressed. The best thing to do is probably to put the config files inside some sub-folder rather than right in the cmake binary dir, so find_package() won't see them.

Done. Can you check it works as expected?
 
> The only other remaining thing is to add the missing #define switches into config.h. I.e. any #defines set by dlib/CMakeLists.txt need to be echoed into the config.h file. So this includes DLIB_ENABLE_STACK_TRACE, DLIB_NO_GUI_SUPPORT, and DLIB_ISO_CPP_ONLY.

Done.

The PR has also been rebased on current master.

**Comment by davisking** [comment]
Sweet, nice work :)  I just merged it in.

**Pull request merged**
