### PR TITLE
Only trigger CI when relevant files are changed

### PR DESCRIPTION
**Pull request by arrufat**

### CODE REVIEW

**Comment by davisking** [comment]
Yeah I was just thinking about this.  It's pretty much still a "run everything that takes any time to run" situation though :shrug:

**Comment by davisking** [comment]
Thanks :)

**Comment by arrufat** [comment]
Yeah, maybe we could go crazy with the paths and make a really complicated configuration that only runs the tests associated with the paths that changed…

At least, with this PR, editing documentation or other non-code stuff won't trigger GitHub Actions.

**Comment by davisking** [comment]
Yep. And editing the ci config files only reruns that one config. Which is nice for trying to puzzle out what the config script is supposed to be for somethings.

**Comment by arrufat** [comment]
Maybe it would be easier to have the CI scripts just run a Python or Shell script, that performs the git diff between `HEAD` and `HEAD~1`, checks which files changed and has all the logic to decide which tests to build and run.

**Comment by davisking** [comment]
Eh don't worry about it. Current setup is plenty good :)

**Pull request merged**
