### PR TITLE
Image alignment and saving using Python

### PR DESCRIPTION
**Pull request by visionworkz**
Thank you for accepting my earlier code and adding it to dlib.

Here I have just added the size and padding as optional parameters for save_face_chip

### CODE REVIEW

**Comment by visionworkz** [comment]
Getting face chips aids in alignment as mentioned in this issue:
https://github.com/davisking/dlib/issues/121

**Comment by davisking** [comment]
Thanks for another PR.  It generally looks good.  But you should clean up the example program.  For instance, why does it include the face recognition stuff when it isn't used?

**Comment by visionworkz** [comment]
Thanks for your feedback @davisking. I have cleaned up the file.

**Comment by visionworkz** [comment]
One thing I noticed is that calling save_face_chips frequently from Python (for example, once every time a face is detected, and also from different processes) results in some corrupt JPEG files though no error is thrown.

**Comment by davisking** [comment]
Maybe you are writing to the same file?

**Comment by visionworkz** [comment]
No. The file prefix I'm passing down is:
`datetime.datetime.now().isoformat()`

So for every batch of faces to be written to disk, the file prefix is quite unique.

I will try adding a UUID to it as well.

I looked at the code for save_jpeg, at first I thought it might be a memory problem if it is async. But looking at the code, it seems to be a sync call.

**Comment by davisking** [comment]
I highly doubt it's something in libpng or dlib.  Python has horrible
support for multi-threading.  It's probably just a bug in how you are using
python.

**Comment by visionworkz** [comment]
I'm using Python mainly to crawl datasets and build live (anonymous) ones while people pass by a camera.

**Comment by davisking** [comment]
Looks good.  Thanks for another PR :)

**Pull request merged**
