### PR TITLE
Unreachable code, fixed compiler warning

### PR DESCRIPTION
**Pull request by rggjan**

### CODE REVIEW

**Comment by davisking** [comment]
Oh yeah, that is weird.  Oops :)

But really, the change should be to remove the first return and keep the second.  Otherwise the code still looks odd.

**Comment by rggjan** [comment]
Both of them would work, I guess :)

**Comment by davisking** [comment]
Right, but if we are changing it we should make it nice :)

**Comment by rggjan** [comment]
Depends on if nice=short/stylish or nice=readable/understandable ;)

**Comment by davisking** [comment]
It's always readable.  

In any event, I want the code to be readable.  I would make the change myself but then I have to reject the PR.  Or you can make the change and I'll merge the PR.  Either way is fine with me :)

**Comment by davisking** [comment]
Sweet, thanks for the PR :)

**Pull request merged**
