### PR TITLE
type_safe_union : visit() and apply_to_contents() performance improvements

### PR DESCRIPTION
**Pull request by pfeatherstone**

### CODE REVIEW

**Comment by pfeatherstone** [comment]
I want to address the bad inlining issue with `visit()` and `apply_to_contents()` as described in https://www.youtube.com/watch?v=va9I2qivBOA and https://mpark.github.io/programming/2019/01/22/variant-visitation-v2/. Not done yet. So far I've just merged `visit()` and `apply_to_contents()`. But maybe it's wasted effort doing it as people should be using std::variant anyway. I use type_safe_union in a few places so it bothers me that it's sub-optimal.

**Comment by pfeatherstone** [comment]
There is also the problem that if all the alternative types are trivial then `type_safe_union` should also be trivial, but it isn't (unlike `std::variant`), so an instance of `type_safe_union` can never be stored in registers. Furthermore, if all types are trivial, then copy, move and destruction should be trivial too. That also contributes to bloated assembly code. That's a lot of work to get right and maybe there is no point. `type_safe_union` isn't built to be optimal, just functional. Still annoying though. I'll leave this open for now, but it might be worth closing as I'm probably the only person using this in anger.

**Comment by pfeatherstone** [comment]
[CMakeLists.txt](https://github.com/davisking/dlib/files/9021066/CMakeLists.txt)
[main.cpp.txt](https://github.com/davisking/dlib/files/9021068/main.cpp.txt)

**Comment by pfeatherstone** [comment]
With latest commit, using a recursive dispatcher I get:
```
N = 1        ; niteration 10000    ; time 0                us ; sum 0              
N = 2        ; niteration 10000    ; time 9460             us ; sum 25000000       
N = 3        ; niteration 10000    ; time 46341            us ; sum 49980000       
N = 5        ; niteration 10000    ; time 55401            us ; sum 100000000      
N = 8        ; niteration 10000    ; time 68011            us ; sum 175000000      
N = 15       ; niteration 10000    ; time 78264            us ; sum 349650000      
N = 32       ; niteration 10000    ; time 134766           us ; sum 773760000      
N = 65       ; niteration 10000    ; time 275226           us ; sum 1580800000     
N = 128      ; niteration 10000    ; time 509940           us ; sum 3169920000     
N = 200      ; niteration 10000    ; time 775182           us ; sum 4975000000 
```
This is a lot better than dlib::master across the board. However, for large N, it's worse than last commit.

**Comment by pfeatherstone** [comment]
Using clang++-10 I get the following using dlib::master:
```
N = 1        ; niteration 10000    ; time 90350            us ; sum 0              
N = 2        ; niteration 10000    ; time 88848            us ; sum 25000000       
N = 3        ; niteration 10000    ; time 79666            us ; sum 49980000       
N = 5        ; niteration 10000    ; time 111062           us ; sum 100000000      
N = 8        ; niteration 10000    ; time 146617           us ; sum 175000000      
N = 15       ; niteration 10000    ; time 203918           us ; sum 349650000      
N = 32       ; niteration 10000    ; time 405405           us ; sum 773760000      
N = 65       ; niteration 10000    ; time 769819           us ; sum 1580800000     
N = 128      ; niteration 10000    ; time 1567939          us ; sum 3169920000     
N = 200      ; niteration 10000    ; time 2343111          us ; sum 4975000000 
```
Again using clang++-10, and [pfeatherstone:tsu_visit_improvement](https://github.com/pfeatherstone/dlib/tree/tsu_visit_improvement) I get:
```
N = 1        ; niteration 10000    ; time 0                us ; sum 0              
N = 2        ; niteration 10000    ; time 47522            us ; sum 25000000       
N = 3        ; niteration 10000    ; time 27139            us ; sum 49980000       
N = 5        ; niteration 10000    ; time 17130            us ; sum 100000000      
N = 8        ; niteration 10000    ; time 16940            us ; sum 175000000      
N = 15       ; niteration 10000    ; time 15730            us ; sum 349650000      
N = 32       ; niteration 10000    ; time 15631            us ; sum 773760000      
N = 65       ; niteration 10000    ; time 96664            us ; sum 1580800000     
N = 128      ; niteration 10000    ; time 424539           us ; sum 3169920000     
N = 200      ; niteration 10000    ; time 714772           us ; sum 4975000000
```

**Comment by pfeatherstone** [comment]
I think the `dispatcher` object could use  bisection for finding the compile time index rather than linear search. Maybe that would improve performance on average and particularly for large  N

**Comment by davisking** [comment]
Yeah I like it :)

You good with how it is?  I'll merge it is so.  Looks good to me in its current state.

**Comment by pfeatherstone** [comment]
Well it's better but don't know if it's the best it can be. I think it's worth merging now. I'll never be happy i can't beat std::variant but oh well. The folks who work on libstdc++ and libc++ are on another level.

**Comment by pfeatherstone** [comment]
I still don't understand why an array of function pointers isn't easily inline-able, particularly if all functions are known at compile time. The compiler can do all sorts of crazy stuff and optimise away so many things, but a vtable essentially is impossible. Weird

**Comment by davisking** [comment]
> I still don't understand why an array of function pointers isn't easily inline-able, particularly if all functions are known at compile time. The compiler can do all sorts of crazy stuff and optimise away so many things, but a vtable essentially is impossible. Weird

Yeah, but it's an unusual thing for people to do so not mind blowing that the gcc devs didn't optimize for it :shrug:

**Pull request merged**
