### PR TITLE
Fixes https://github.com/davisking/dlib/issues/2350

### PR DESCRIPTION
**Pull request by pfeatherstone**
This fixes https://github.com/davisking/dlib/issues/2350

### CODE REVIEW

**Comment by pfeatherstone** [comment]
Oh, and I've amended the previous commit message (type_safe_union stuff) to make it more succinct (I need to get better at using git).

**Comment by davisking** [comment]
Nice, thanks.  Can you clean up this PR though?  It's got changes from the last PR you submitted in it.  Like check out the `Files changed` tab.

You can't amend commits that are already landed in the master branch.  I mean, you can amend and history edit locally, but pushing them to a repo that already has those changes isn't going to work.

**Comment by pfeatherstone** [comment]
Balls. Yep sorry about that. I won't have time to touch this until Monday. Given how small this is, maybe it's easier if you commit straight to master and I'll close this.

**Comment by davisking** [comment]
Merged it in.

**Pull request closed without merging**
